services:
  cli_debrid:
    image: godver3/cli_debrid:dev
    pull_policy: always
    container_name: cli_debrid-dev
    ports:
      - "5000:5000"
    volumes:
      - ./db_content:/app/db_content
      - ./config:/app/config
      - ./logs:/app/logs
    environment:
      - TZ=America/Edmonton
    restart: unless-stopped
    tty: true
    stdin_open: true
