version: '3.8'

services:

  cli_debrid:
    image: godver3/cli_debrid:latest
    pull_policy: always
    container_name: cli_debrid
    ports:
      - "5000:5000"
    volumes:
      - cli_debrid_data:/user
    environment:
      - TZ=America/Edmonton
    restart: unless-stopped
    tty: true
    stdin_open: true

  db:
    image: postgres:13
    container_name: cli_battery_db
    environment:
      POSTGRES_DB: cli_battery_database
      POSTGRES_USER: cli_debrid
      POSTGRES_PASSWORD: cli_debrid
    volumes:
      - cli_postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - cli_network

  cli_battery:
    build: .
    container_name: cli_battery_app
    environment:
      - DATABASE_URL=postgresql://cli_debrid:cli_debrid@db:5432/cli_battery_database
    volumes:
      - cli_battery_data:/user
    depends_on:
      - db
    ports:
      - "50051:50051"
      - "5001:5001"
    networks:
      - cli_network

networks:
  cli_network:
    name: cli_network

volumes:
  cli_postgres_data:
  cli_battery_data:
  cli_debrid_data: