services:
  cli_debrid:
    image: godver3/cli_debrid:dev
    pull_policy: always
    container_name: cli_debrid
    ports:
      - "5000:5000"
      - "5001:5001"
      - "8888:8888"
    volumes:
      - /host/location/db_content:/user/db_content
      - /host/location/config:/user/config
      - /host/location/logs:/user/logs
      - /mnt:/mnt
      - /host/location/phalanx_db_hyperswarm/autobase_storage_v4:/app/phalanx_db_hyperswarm/autobase_storage_v4
    environment:
      - TZ=America/Edmonton
    restart: unless-stopped
    tty: true
    stdin_open: true
