services:
  cli_debrid:
    image: godver3/cli_debrid:dev
    pull_policy: always
    container_name: cli_debrid
    ports:
      - "5000:5000"
      - "5001:5001"
      - "8888:8888"
    volumes:
      - /host/location/db_content:/user/db_content
      - /host/location/config:/user/config
      - /host/location/logs:/user/logs
      - /mnt:/mnt
      - /host/location/p2p-db-storage:/app/p2p-db-storage
      - /host/location/db_data:/app/db_data
    environment:
      - TZ=America/Edmonton
    restart: unless-stopped
    tty: true
    stdin_open: true
