version: '3.8'

services:

  cli_debrid:
    image: godver3/cli_debrid:dev
    pull_policy: always
    container_name: cli_debrid_app
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - cli_debrid_data:/user
    environment:
      - TZ=America/Edmonton
    restart: unless-stopped
    tty: true
    stdin_open: true
    networks:
      - cli_debrid

networks:
  cli_debrid:
    name: cli_debrid
    driver: bridge

volumes:
  cli_debrid_data: