#!/usr/bin/env python3
"""
nzbdav setup & migration assistant for cli-debrid.

Generates the Docker/rclone/config files for an NzbDAV usenet backend and walks
you through either a FRESH install or a migration FROM cli_mount — so a new user
can get started, and a cli_mount user can switch, without rediscovering every
gotcha by hand. Generic and stdlib-only: it prompts for your paths/credentials
and writes templated files; it does not hard-code one person's setup.

It is SAFE by default: it writes files into an output directory and prints the
exact next commands. It never starts containers or edits your live config unless
you explicitly pass --write-config / run the migrate-files step.

Subcommands
-----------
  wizard          Interactive walk-through (fresh or migrate). Recommended.
  generate        Non-interactive: write compose + rclone.conf + config block.
  migrate-files   Replay existing cli_mount .nzb files into NzbDAV (file move).
  check           Reminder to run the preflight doctor (nzbdav_migrate.py).

Examples
--------
  python3 nzbdav_setup.py wizard
  python3 nzbdav_setup.py generate --nzbdav-host 192.168.1.50 --apikey KEY \\
      --mount-base /srv/DUMB/mnt --out ./nzbdav-generated
  python3 nzbdav_setup.py migrate-files --nzbdav-host 192.168.1.50 --apikey KEY \\
      --climount-container climount

After generating: review the files, add the categories (printed), `docker compose
up -d` the nzbdav stack, set cli-debrid's Usenet Provider config, restart
cli-debrid, then run nzbdav_migrate.py to verify.
"""

import argparse
import json
import os
import shutil
import subprocess
import sys
import time
import urllib.parse
import urllib.request

# Categories cli-debrid's title heuristic routes video grabs into, plus the
# catch-all fallback. These must exist in NzbDAV (api.categories) or submits are
# rejected. 'music' is recommended (the heuristic can emit it) though cli-debrid
# rarely grabs music.
DEFAULT_CATEGORIES = [
    'movies', 'shows',
    'movies_1080p', 'shows_1080p',
    'movies_2160p', 'shows_2160p',
    'movies_1080p_remux', 'movies_2160p_remux',
    'anime_movies', 'anime_shows',
    '__unplayable__', 'music',
]

# cli_mount-folder -> NzbDAV-category mapping used when replaying files. Edit via
# --category-map k=v,k=v. Defaults map cli_mount's content folders to the cli-debrid
# heuristic category names so replayed files land where cli-debrid/Plex expect them.
DEFAULT_CATEGORY_MAP = {
    'movies': 'movies',
    'movies_1080p': 'movies_1080p',
    'movies_2160p': 'movies_2160p',
    'movies_1080p_remux': 'movies_1080p_remux',
    'movies_2160p_remux': 'movies_2160p_remux',
    'shows': 'shows',
    'shows_1080p': 'shows_1080p',
    'shows_2160p': 'shows_2160p',
    'anime_movies': 'anime_movies',
    'anime_shows': 'anime_shows',
    '__unplayable__': '__unplayable__',
    'music': 'music',
}

COMPOSE_TEMPLATE = """\
# NzbDAV usenet backend for cli-debrid — generated by nzbdav_setup.py
# Two services: nzbdav (SAB-compatible API + WebDAV) and an rclone sidecar that
# mounts NzbDAV's WebDAV so cli-debrid/Plex can read the files.
services:
  nzbdav:
    image: nzbdav/nzbdav:latest
    container_name: nzbdav
    restart: unless-stopped
    ports:
      - "{port}:3000"
    environment:
      - PUID={puid}
      - PGID={pgid}
      - TZ={tz}
      # Lets SAB clients (cli-debrid, Lidarr, …) hit /api?apikey=... without the
      # React frontend redirecting to /login. SAB api.key + WebDAV auth still apply.
      - DISABLE_FRONTEND_AUTH=true
    volumes:
      - ./config:/config
      # Parent-bind (not the mount-target directly) avoids a FUSE-mount conflict;
      # rclone mounts the nzbdav subdir inside this bind.
      - {mount_base}:/mnt/remote:rshared
    healthcheck:
      test: curl -f http://localhost:3000/health || exit 1
      interval: 1m
      retries: 3
      start_period: 30s
      timeout: 5s
    networks:
      - nzbdav_net

  nzbdav_rclone:
    image: rclone/rclone:latest
    container_name: nzbdav_rclone
    restart: unless-stopped
    environment:
      - PUID={puid}
      - PGID={pgid}
      - TZ={tz}
    volumes:
      - {mount_base}:/mnt/remote:rshared
      - ./rclone.conf:/config/rclone/rclone.conf
      - {vfs_cache}:/cache
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse:/dev/fuse:rwm
    depends_on:
      nzbdav:
        condition: service_healthy
    command: >
      mount nzbdav: /mnt/remote/nzbdav
        --uid={puid} --gid={pgid}
        --allow-other --links --use-cookies
        --vfs-cache-mode=full
        --vfs-cache-max-size={vfs_size}
        --vfs-cache-max-age=24h
        --buffer-size=0M
        --vfs-read-ahead=128M
        --vfs-read-chunk-size=8M
        --vfs-read-chunk-size-limit=64M
        --dir-cache-time=20s
        --cache-dir=/cache
        --log-level=INFO
    networks:
      - nzbdav_net

networks:
  nzbdav_net:
    driver: bridge
"""

RCLONE_TEMPLATE = """\
[nzbdav]
type = webdav
url = http://nzbdav:3000/
vendor = other
user = {webdav_user}
pass = {webdav_pass}
"""


def prompt(text, default=None):
    suffix = f" [{default}]" if default is not None else ""
    val = input(f"{text}{suffix}: ").strip()
    return val or (default if default is not None else '')


def http_json(url, timeout=15, data=None, method=None):
    req = urllib.request.Request(url, data=data, method=method,
                                 headers={'User-Agent': 'nzbdav-setup/1.0'})
    with urllib.request.urlopen(req, timeout=timeout) as r:
        return json.loads(r.read().decode('utf-8', 'replace'))


def obscure_rclone_pass(plain):
    """Obscure a WebDAV password for rclone.conf if the rclone binary is present.
    Falls back to a clear marker the user must replace."""
    rclone = shutil.which('rclone')
    if rclone and plain:
        try:
            out = subprocess.run([rclone, 'obscure', plain], capture_output=True, text=True, timeout=10)
            if out.returncode == 0 and out.stdout.strip():
                return out.stdout.strip()
        except Exception:
            pass
    return plain  # caller is warned to run: rclone obscure <pass>


# ---------------------------------------------------------------------------
# generate
# ---------------------------------------------------------------------------

def do_generate(a, interactive=False):
    out = os.path.abspath(a.out)
    nzbdav_dir = os.path.join(out, 'nzbdav')
    os.makedirs(os.path.join(nzbdav_dir, 'config'), exist_ok=True)

    pass_obscured = obscure_rclone_pass(a.webdav_pass) if a.webdav_pass else 'RUN: rclone obscure <your-webdav-pass>'
    rclone_pass_warn = (pass_obscured == a.webdav_pass and bool(a.webdav_pass)) or pass_obscured.startswith('RUN:')

    compose = COMPOSE_TEMPLATE.format(
        port=a.port, puid=a.puid, pgid=a.pgid, tz=a.tz,
        mount_base=a.mount_base, vfs_cache=a.vfs_cache, vfs_size=a.vfs_size,
    )
    rclone = RCLONE_TEMPLATE.format(webdav_user=a.webdav_user, webdav_pass=pass_obscured)

    with open(os.path.join(nzbdav_dir, 'docker-compose.yml'), 'w') as f:
        f.write(compose)
    with open(os.path.join(nzbdav_dir, 'rclone.conf'), 'w') as f:
        f.write(rclone)

    # cli-debrid Usenet Provider config block to merge into config.json
    provider_cfg = {
        "Usenet Provider": {
            "enabled": True,
            "provider": "nzbdav",
            "url": f"http://{a.nzbdav_host}:{a.port}",
            "api_token": a.apikey or "<nzbdav api.key>",
            "download_folder": "__unplayable__",
            "mounted_file_location": a.container_mount_path,
            "retention_days": 1500,
            "enable_nzb_naming": False,
        }
    }
    cfg_path = os.path.join(out, 'cli_debrid.usenet_provider.json')
    with open(cfg_path, 'w') as f:
        json.dump(provider_cfg, f, indent=2)

    cats = a.categories or list(DEFAULT_CATEGORIES)
    notes = _setup_notes(a, cats, rclone_pass_warn)
    with open(os.path.join(out, 'SETUP_NOTES.md'), 'w') as f:
        f.write(notes)

    print(f"\nGenerated into: {out}")
    print(f"  nzbdav/docker-compose.yml")
    print(f"  nzbdav/rclone.conf            (WebDAV remote)")
    print(f"  cli_debrid.usenet_provider.json")
    print(f"  SETUP_NOTES.md                (READ THIS — step-by-step)")
    if rclone_pass_warn:
        print("\n  NOTE: rclone password is NOT obscured (rclone binary not found or no pass given).")
        print("        Run `rclone obscure <pass>` and paste the result into nzbdav/rclone.conf.")
    if a.write_config and a.cli_debrid_config:
        _merge_into_config(a.cli_debrid_config, provider_cfg)
    print("\nNext: open SETUP_NOTES.md and follow the steps.")
    return 0


def _setup_notes(a, cats, rclone_pass_warn):
    out_dir = os.path.abspath(a.out)
    catlist = ', '.join(c for c in cats if c != 'music')  # music shown as optional
    return f"""# NzbDAV setup — next steps

Generated for nzbdav at http://{a.nzbdav_host}:{a.port}

## 1. Start the NzbDAV stack
```
cd {os.path.abspath(a.out)}/nzbdav
docker compose up -d
```
Open http://{a.nzbdav_host}:{a.port}, finish first-run setup, and add your usenet
(NNTP) provider + indexers in the NzbDAV UI. Copy the SAB **api.key** (Settings →
API) — cli-debrid needs it.

{"**rclone password**: the generated rclone.conf password is a placeholder/plain — run `rclone obscure <your-webdav-pass>` and paste the result as `pass =`." if rclone_pass_warn else ""}

## 2. Add the categories cli-debrid uses
A "category" is just the sub-folder NzbDAV files land in. cli-debrid auto-sorts
grabs into these — they MUST exist in NzbDAV or submits are rejected (items loop
in "Wanted"):
  Required: {catlist}
  Optional: music  (only if you also grab music; harmless to add)

Easiest — in the NzbDAV web UI: **Settings → Categories**, add each name above.

Or from the command line (for this generated stack the NzbDAV database is at
`{out_dir}/nzbdav/config/db.sqlite`):
```
python3 nzbdav_migrate.py --nzbdav-db {out_dir}/nzbdav/config/db.sqlite --fix
```
That adds only the missing categories (don't hand-write a raw SQL `||` append —
re-running it creates duplicates).

## 3. Bind the nzbdav mount into cli-debrid
Add to cli-debrid's docker-compose volumes (so it can resolve files). Use
`:rshared` — with `:rslave` the mount drops as "Transport endpoint not connected"
after an rclone-sidecar restart:
```
- {a.mount_base}/nzbdav:{a.container_mount_path}:rshared
```
Until PR #425 is merged, also add the overlay binds from this patch (see README).

## 4. Set cli-debrid's Usenet Provider config
Merge cli_debrid.usenet_provider.json into cli-debrid's config.json (Settings →
Required → Usenet Provider), set the api_token to the NzbDAV api.key, then restart
cli-debrid.

## 5. Add the category paths to Plex
| Plex library | Add these folders |
|---|---|
| Movies | {a.container_mount_path}/content/movies , {a.container_mount_path}/content/movies_1080p_264 |
| Shows  | {a.container_mount_path}/content/shows  , {a.container_mount_path}/content/shows_1080p_264 |
Disable Plex auto-scan on these FUSE paths (inotify doesn't propagate); cli-debrid
triggers scans itself.

## 6. Verify
```
python3 nzbdav_migrate.py --config <cli-debrid config.json>
```
Should report no blocking issues.

## (Migration only) Move existing cli_mount files
NzbDAV has no copy of your old grabs. Options:
- **Recommended:** run NzbDAV in parallel and let NEW grabs fill it; let the old
  cli_mount library age out. Robust, no surprises.
- **Replay** old .nzb files (best-effort — cli_mount trims old .nzb files, so a
  large fraction may be unavailable, and some replays double-nest folders):
  ```
  python3 nzbdav_setup.py migrate-files --nzbdav-host {a.nzbdav_host} --port {a.port} \\
      --apikey <api.key> --climount-container climount
  ```
Do NOT hard-swap mounts under Plex — a video section can purge "missing" items.
"""


def _merge_into_config(path, block):
    try:
        with open(path) as f:
            cfg = json.load(f)
        cfg.setdefault('Usenet Provider', {}).update(block['Usenet Provider'])
        bak = path + '.bak.nzbdav_setup'
        if not os.path.exists(bak):
            shutil.copy2(path, bak)
        with open(path, 'w') as f:
            json.dump(cfg, f, indent=2)
        print(f"  merged Usenet Provider block into {path} (backup: {bak})")
    except Exception as e:
        print(f"  WARN: could not merge into {path}: {e}")


# ---------------------------------------------------------------------------
# migrate-files (cli_mount .nzb replay → NzbDAV)
# ---------------------------------------------------------------------------

def do_migrate_files(a):
    base = f"http://{a.nzbdav_host}:{a.port}"
    catmap = dict(DEFAULT_CATEGORY_MAP)
    if a.category_map:
        for pair in a.category_map.split(','):
            if '=' in pair:
                k, v = pair.split('=', 1)
                catmap[k.strip()] = v.strip()

    state_file = os.path.abspath(a.state_file)
    state = {'done': [], 'failed': []}
    if os.path.exists(state_file):
        try:
            state = json.load(open(state_file))
        except Exception:
            pass

    print(f"Replaying cli_mount .nzb files from container '{a.climount_container}' → {base}")
    print("NOTE: best-effort. cli_mount trims old .nzb files; unavailable ones are skipped.\n")

    # Enumerate available .nzb files inside the climount container
    r = subprocess.run(['docker', 'exec', a.climount_container, 'sh', '-c', f'ls {a.climount_nzb_path}'],
                       capture_output=True, text=True)
    if r.returncode != 0:
        print(f"ERROR: cannot list {a.climount_nzb_path} in {a.climount_container}: {r.stderr[:200]}")
        return 1
    nzb_basenames = {f[:-4] for f in r.stdout.split() if f.endswith('.nzb')}
    print(f"Found {len(nzb_basenames)} replayable .nzb files in cli_mount.")

    # Build work list from the mounted climount content folders
    work = []
    for decy_cat, nz_cat in catmap.items():
        folder = os.path.join(a.climount_mount, decy_cat)
        if not os.path.isdir(folder):
            continue
        for release in os.listdir(folder):
            key = f"{decy_cat}/{release}"
            if key in state['done'] or key in state['failed']:
                continue
            if release in nzb_basenames:
                work.append((decy_cat, nz_cat, release))
    print(f"Work list: {len(work)} releases with a replayable .nzb.\n")
    if not work:
        print("Nothing to replay (no matching .nzb files). Consider parallel-fill instead.")
        return 0

    staging = '/tmp/nzbdav_replay_staging'
    os.makedirs(staging, exist_ok=True)
    for i, (decy_cat, nz_cat, release) in enumerate(work, 1):
        key = f"{decy_cat}/{release}"
        # throttle on queue depth
        _wait_queue(base, a.apikey, a.max_queue)
        local = os.path.join(staging, f"{release}.nzb")
        cp = subprocess.run(['docker', 'cp', f"{a.climount_container}:{a.climount_nzb_path}/{release}.nzb", local],
                           capture_output=True, text=True)
        if cp.returncode != 0:
            state['failed'].append(f"{key} (copy-fail)"); _save(state, state_file); continue
        nzo = _submit(base, a.apikey, local, release, nz_cat)
        try:
            os.unlink(local)
        except OSError:
            pass
        if nzo:
            print(f"[{i}/{len(work)}] OK   {key} → {nz_cat} ({nzo[:8]})")
            state['done'].append(key)
        else:
            print(f"[{i}/{len(work)}] FAIL {key} (submit)")
            state['failed'].append(f"{key} (submit-fail)")
        _save(state, state_file)
    print(f"\nDone: {len(state['done'])} replayed, {len(state['failed'])} failed. State: {state_file}")
    return 0


def _wait_queue(base, key, max_slots, poll=2, max_wait=180):
    waited = 0
    while waited < max_wait:
        try:
            q = http_json(f"{base}/api?mode=queue&apikey={key}")['queue']
            if int(q.get('noofslots', 0)) < max_slots:
                return
        except Exception:
            pass
        time.sleep(poll); waited += poll


def _submit(base, key, nzb_path, release, cat):
    # multipart upload via curl (stdlib multipart is clumsy); curl is ubiquitous
    url = (f"{base}/api?mode=addfile&apikey={key}&cat={cat}"
           f"&nzbname={urllib.parse.quote(release)}")
    r = subprocess.run(['curl', '-s', '--max-time', '30', '-X', 'POST', url, '-F', f'name=@{nzb_path}'],
                       capture_output=True, text=True)
    try:
        d = json.loads(r.stdout)
        if d.get('status') and d.get('nzo_ids'):
            return d['nzo_ids'][0]
    except json.JSONDecodeError:
        pass
    return None


def _save(state, path):
    with open(path, 'w') as f:
        json.dump(state, f, indent=2)


# ---------------------------------------------------------------------------
# wizard
# ---------------------------------------------------------------------------

def do_wizard(a):
    print("== NzbDAV setup assistant ==\n")
    scenario = prompt("Scenario — (f)resh install or (m)igrate from cli_mount?", "f").lower()
    a.nzbdav_host = prompt("NzbDAV host/IP cli-debrid will reach", a.nzbdav_host)
    a.port = prompt("NzbDAV port", a.port)
    a.apikey = prompt("NzbDAV SAB api.key (blank if not created yet)", a.apikey)
    a.mount_base = prompt("Host path mapped to /mnt/remote (parent of the nzbdav mount)", a.mount_base)
    a.container_mount_path = prompt("Path cli-debrid sees the nzbdav mount at", a.container_mount_path)
    a.vfs_cache = prompt("Host path for rclone vfs cache", a.vfs_cache)
    a.vfs_size = prompt("rclone vfs cache max size", a.vfs_size)
    print("  (WebDAV user/password = the credentials you set in NzbDAV → Settings →")
    print("   WebDAV. These are NOT the SAB api.key. If you haven't set them yet, do")
    print("   that in the NzbDAV UI first, then enter them here.)")
    a.webdav_user = prompt("NzbDAV WebDAV user (for rclone)", a.webdav_user)
    a.webdav_pass = prompt("NzbDAV WebDAV password (will be rclone-obscured if possible)", a.webdav_pass)
    a.out = prompt("Output directory for generated files", a.out)
    rc = do_generate(a, interactive=True)
    if scenario.startswith('m'):
        print("\n--- Migration ---")
        print("Generated files set up NzbDAV alongside cli_mount. For the existing")
        print("library, the recommended path is parallel-fill (let new grabs populate")
        print("NzbDAV). If you want to attempt replaying old .nzb files, run:")
        print(f"  python3 {os.path.basename(__file__)} migrate-files --nzbdav-host {a.nzbdav_host} "
              f"--port {a.port} --apikey <api.key> --climount-container climount")
    return rc


def build_parser():
    p = argparse.ArgumentParser(description='NzbDAV setup & migration assistant for cli-debrid')
    sub = p.add_subparsers(dest='cmd')

    def add_common(sp):
        sp.add_argument('--nzbdav-host', default='localhost')
        sp.add_argument('--port', default='3000')
        sp.add_argument('--apikey', default='')

    g = sub.add_parser('generate', help='write compose + rclone.conf + config block')
    add_common(g)
    g.add_argument('--mount-base', default='/srv/DUMB/mnt', help='host path mapped to /mnt/remote')
    g.add_argument('--container-mount-path', default='/mnt/nzbdav', help='where cli-debrid sees the mount')
    g.add_argument('--vfs-cache', default='/mnt/cache/nzbdav-vfs')
    g.add_argument('--vfs-size', default='30G')
    g.add_argument('--webdav-user', default='rclone')
    g.add_argument('--webdav-pass', default='')
    g.add_argument('--puid', default='1000'); g.add_argument('--pgid', default='1000')
    g.add_argument('--tz', default='Etc/UTC')
    g.add_argument('--categories', type=lambda s: [c.strip() for c in s.split(',') if c.strip()], default=None)
    g.add_argument('--out', default='./nzbdav-generated')
    g.add_argument('--cli-debrid-config', default='')
    g.add_argument('--write-config', action='store_true', help='merge the provider block into --cli-debrid-config')

    w = sub.add_parser('wizard', help='interactive walk-through')
    add_common(w)
    w.add_argument('--mount-base', default='/srv/DUMB/mnt')
    w.add_argument('--container-mount-path', default='/mnt/nzbdav')
    w.add_argument('--vfs-cache', default='/mnt/cache/nzbdav-vfs')
    w.add_argument('--vfs-size', default='30G')
    w.add_argument('--webdav-user', default='rclone'); w.add_argument('--webdav-pass', default='')
    w.add_argument('--puid', default='1000'); w.add_argument('--pgid', default='1000'); w.add_argument('--tz', default='Etc/UTC')
    w.add_argument('--categories', default=None)
    w.add_argument('--out', default='./nzbdav-generated')
    w.add_argument('--cli-debrid-config', default=''); w.add_argument('--write-config', action='store_true')

    m = sub.add_parser('migrate-files', help='replay cli_mount .nzb files into NzbDAV (best-effort)')
    add_common(m)
    m.add_argument('--climount-container', default='climount')
    m.add_argument('--climount-nzb-path', default='/app/usenet/nzbs', help='.nzb store inside the container')
    m.add_argument('--climount-mount', default='/srv/DUMB/mnt/debrid/climount', help='host path of climount content folders')
    m.add_argument('--category-map', default='', help='climount_cat=nzbdav_cat,comma-separated')
    m.add_argument('--max-queue', type=int, default=3, help='throttle: keep nzbdav queue below this')
    m.add_argument('--state-file', default='./nzbdav_replay.state.json')

    sub.add_parser('check', help='reminder to run the preflight doctor')
    return p


def main():
    p = build_parser()
    a = p.parse_args()
    if a.cmd == 'generate':
        return do_generate(a)
    if a.cmd == 'wizard':
        return do_wizard(a)
    if a.cmd == 'migrate-files':
        return do_migrate_files(a)
    if a.cmd == 'check':
        print("Run the preflight doctor:\n  python3 nzbdav_migrate.py --config <cli-debrid config.json>")
        return 0
    p.print_help()
    return 1


if __name__ == '__main__':
    sys.exit(main())
