[zurg]
type = webdav
url = http://debrid_zurg:9999/dav/
vendor = other
pacer_min_sleep = 0

[torbox-temp]
type = webdav
url = http://localhost:8282/webdav/torbox
vendor = other
user = liam.d.hughes@gmail.com
pass = yhbwDqPJv-dAJaO_LRrKS-8Nf-lx-Ttfpwc
